### ISSUE TITLE
I have updated the packaging to be a little more slick. In case its needed, I am willing to help with the maintenance of the snap package at least for the first few months.

### ISSUE THREAD

**Issue by royalsg22** [httpie/httpie#1116]
I have updated the packaging to be a little slicker. In case it's needed, I am willing to help with the maintenance of the snap package at least for the first few months.
```
name: httpie
base: core18
version: git
summary: HTTPie - a CLI, cURL-like tool for humans.
description: |
  HTTPie (pronounced aitch-tee-tee-pie) is a command-line HTTP client.
  Its goal is to make CLI interaction with web services as human-friendly as possible.
  It provides a simple HTTP command that allows for sending arbitrary HTTP requests using a simple and natural syntax, and displays colorized output.

   HTTPie can be used for testing, debugging, and generally interacting with HTTP servers.

grade: stable
confinement: strict

parts:
  httpie:
    plugin: python
    source: .
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m compileall -q $SNAPCRAFT_PRIME

apps:
  http:
    command: http
    plugs:
      - home
      - network
```

_Originally posted by @om26er in https://github.com/httpie/httpie/issues/672#issuecomment-485904969_
Set1/Repo/"B"/import os
Set2/Repo/"C"/import os
Set3/Repo/"D"/import os
Set4/Repo/"E"/import os
Set5/Repo/"F"/import os
Set6/Repo/"G"/import os
Set7/Repo/"H"/import os
Set8/Repo/"I"/import os
