### ISSUE TITLE
Support snap package on Linux

### ISSUE THREAD

**Issue by om26er** [httpie/httpie#672]
A ‘snap’ is a universal Linux package https://www.ubuntu.com/desktop/snappy, they are especially useful on servers (on desktops too), where they allow to install apps quickly with a single command and in an isolated way.

There is a supporting service build.snapcraft.io, which allows for automatic builds of the source whenever anything changes on a github repo.

I have done initial packaging and it seems to work fine. Below example shows how simple (and readable) the build config will be, if you decide to publish httpie as snap.
```
name: httpie
version: '0.9.9'
summary: HTTPie - a CLI, cURL-like tool for humans.
description: |
  HTTPie (pronounced aitch-tee-tee-pie) is a command line HTTP client.
  Its goal is to make CLI interaction with web services as human-friendly as possible.
  It provides a simple http command that allows for sending arbitrary HTTP requests
  using a simple and natural syntax, and displays colorized output.

   HTTPie can be used for testing, debugging, and generally interacting with HTTP servers.

grade: devel
confinement: strict

parts:
  httpie:
    plugin: python
    source: https://github.com/jakubroztocil/httpie.git

apps:
  http:
    command: http
    plugs:
      - home
      - network
```
